# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: eth_udp_loop.xdc

# IP: ip/async_fifo_2048x8b/async_fifo_2048x8b.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==async_fifo_2048x8b || ORIG_REF_NAME==async_fifo_2048x8b} -quiet] -quiet
