set_property -dict {PACKAGE_PIN G15 IOSTANDARD LVCMOS33} [get_ports eth_rst_n]
set_property -dict {PACKAGE_PIN K17 IOSTANDARD LVCMOS33} [get_ports eth_rxc]
set_property -dict {PACKAGE_PIN E17 IOSTANDARD LVCMOS33} [get_ports eth_rx_ctl]
set_property -dict {PACKAGE_PIN B19 IOSTANDARD LVCMOS33} [get_ports {eth_rxd[0]}]
set_property -dict {PACKAGE_PIN A20 IOSTANDARD LVCMOS33} [get_ports {eth_rxd[1]}]
set_property -dict {PACKAGE_PIN H17 IOSTANDARD LVCMOS33} [get_ports {eth_rxd[2]}]
set_property -dict {PACKAGE_PIN H16 IOSTANDARD LVCMOS33} [get_ports {eth_rxd[3]}]

set_property -dict {PACKAGE_PIN B20 IOSTANDARD LVCMOS33} [get_ports eth_txc]
set_property -dict {PACKAGE_PIN K18 IOSTANDARD LVCMOS33} [get_ports eth_tx_ctl]
set_property -dict {PACKAGE_PIN D18 IOSTANDARD LVCMOS33} [get_ports {eth_txd[0]}]
set_property -dict {PACKAGE_PIN C20 IOSTANDARD LVCMOS33} [get_ports {eth_txd[1]}]
set_property -dict {PACKAGE_PIN D19 IOSTANDARD LVCMOS33} [get_ports {eth_txd[2]}]
set_property -dict {PACKAGE_PIN D20 IOSTANDARD LVCMOS33} [get_ports {eth_txd[3]}]


create_clock -period 20.000 -name sys_clk [get_ports sys_clk]
create_clock -period 8.000 -name eth_rxc [get_ports eth_rxc]
set_property -dict {PACKAGE_PIN U18 IOSTANDARD LVCMOS33} [get_ports sys_clk]
set_property -dict {PACKAGE_PIN N16 IOSTANDARD LVCMOS33} [get_ports sys_rst_n]







set_property PACKAGE_PIN V16 [get_ports {DB15_0[0]}]
set_property PACKAGE_PIN W16 [get_ports {DB15_0[1]}]
set_property PACKAGE_PIN T14 [get_ports {DB15_0[2]}]
set_property PACKAGE_PIN T15 [get_ports {DB15_0[3]}]
set_property PACKAGE_PIN Y17 [get_ports {DB15_0[4]}]
set_property PACKAGE_PIN Y16 [get_ports {DB15_0[5]}]
set_property PACKAGE_PIN T16 [get_ports {DB15_0[6]}]
set_property PACKAGE_PIN U17 [get_ports {DB15_0[7]}]
set_property PACKAGE_PIN R17 [get_ports {DB15_0[8]}]
set_property PACKAGE_PIN R16 [get_ports {DB15_0[9]}]
set_property PACKAGE_PIN W19 [get_ports {DB15_0[10]}]
set_property PACKAGE_PIN W18 [get_ports {DB15_0[11]}]
set_property PACKAGE_PIN P16 [get_ports {DB15_0[12]}]
set_property PACKAGE_PIN P15 [get_ports {DB15_0[13]}]
set_property PACKAGE_PIN Y19 [get_ports {DB15_0[14]}]
set_property PACKAGE_PIN Y18 [get_ports {DB15_0[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DB15_0[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DB15_0[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DB15_0[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DB15_0[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DB15_0[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DB15_0[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DB15_0[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DB15_0[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DB15_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DB15_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DB15_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DB15_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DB15_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DB15_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DB15_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {DB15_0[0]}]
set_property PACKAGE_PIN J14 [get_ports CSB]
set_property PACKAGE_PIN L16 [get_ports DCO]
set_property PACKAGE_PIN V18 [get_ports OEB]
set_property PACKAGE_PIN V17 [get_ports OTR]
set_property PACKAGE_PIN M15 [get_ports PDWM]
set_property PACKAGE_PIN R18 [get_ports SCLK]
set_property PACKAGE_PIN K14 [get_ports SDIO]

set_property IOSTANDARD LVCMOS33 [get_ports CSB]
set_property IOSTANDARD LVCMOS33 [get_ports DCO]
set_property IOSTANDARD LVCMOS33 [get_ports OEB]
set_property IOSTANDARD LVCMOS33 [get_ports OTR]
set_property IOSTANDARD LVCMOS33 [get_ports SCLK]
set_property IOSTANDARD LVCMOS33 [get_ports PDWM]
set_property IOSTANDARD LVCMOS33 [get_ports SDIO]

