# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "D:/Project/FPGA/temporary/cc/41_eth_udp_loop/prj/.Xil/Vivado-3036-LEGION2020/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7z010clg400-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv {
      F:/Software/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      F:/Software/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog {
      D:/Project/FPGA/temporary/cc/41_eth_udp_loop/prj/.Xil/Vivado-3036-LEGION2020/realtime/async_fifo_2048x8b_stub.v
      D:/Project/FPGA/temporary/cc/41_eth_udp_loop/rtl/arp/arp.v
      D:/Project/FPGA/temporary/cc/41_eth_udp_loop/rtl/arp/arp_rx.v
      D:/Project/FPGA/temporary/cc/41_eth_udp_loop/rtl/arp/arp_tx.v
      D:/Project/FPGA/temporary/cc/41_eth_udp_loop/rtl/arp/crc32_d8.v
      D:/Project/FPGA/temporary/cc/41_eth_udp_loop/rtl/eth_ctrl.v
      D:/Project/FPGA/temporary/cc/41_eth_udp_loop/rtl/gmii_to_rgmii/gmii_to_rgmii.v
      D:/Project/FPGA/temporary/cc/41_eth_udp_loop/rtl/icmp/icmp.v
      D:/Project/FPGA/temporary/cc/41_eth_udp_loop/rtl/icmp/icmp_rx.v
      D:/Project/FPGA/temporary/cc/41_eth_udp_loop/rtl/icmp/icmp_tx.v
      D:/Project/FPGA/temporary/cc/41_eth_udp_loop/rtl/gmii_to_rgmii/rgmii_rx.v
      D:/Project/FPGA/temporary/cc/41_eth_udp_loop/rtl/gmii_to_rgmii/rgmii_tx.v
      D:/Project/FPGA/temporary/cc/41_eth_udp_loop/rtl/udp/udp.v
      D:/Project/FPGA/temporary/cc/41_eth_udp_loop/rtl/udp/udp_rx.v
      D:/Project/FPGA/temporary/cc/41_eth_udp_loop/rtl/udp/udp_tx.v
      D:/Project/FPGA/temporary/cc/41_eth_udp_loop/rtl/eth_udp_loop.v
    }
      rt::read_vhdl -lib xpm F:/Software/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top eth_udp_loop
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "D:/Project/FPGA/temporary/cc/41_eth_udp_loop/prj/.Xil/Vivado-3036-LEGION2020/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
