######################################################################
#
# File name : tb_udp_compile.do
# Created on: Mon Jul 10 17:01:35 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\modeltech64_10.5\\win64\\vlib modelsim_lib/work
C:\\modeltech64_10.5\\win64\\vlib modelsim_lib/msim

C:\\modeltech64_10.5\\win64\\vlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.5\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.5\\win64\\vlog  -incr -work xil_defaultlib  \
"../../../../../rtl/arp/crc32_d8.v" \
"../../../../../rtl/udp/udp.v" \
"../../../../../rtl/udp/udp_rx.v" \
"../../../../../rtl/udp/udp_tx.v" \
"../../../../../sim/tb/tb_udp.v" \


# compile glbl module
C:\\modeltech64_10.5\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

