######################################################################
#
# File name : tb_udp_wave.do
# Created on: Wed Jul 05 09:21:48 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
