######################################################################
#
# File name : tb_udp.udo
# Created on: Wed Jul 05 09:21:48 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
